id: ABDDA2BAC
title: 'Chapter 9: Vīryapāramitā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:18:57.379412
  last_modified_at: 2022-03-01 21:18:57.379415
