id: ABDDA2BAC
title: 'Chapter 11: Praj침캐p캐ramit캐'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:18:57.371684
  last_modified_at: 2022-03-01 21:18:57.371689
