id: ABDDA2BAC
title: CI_Folio 2a
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:18:57.226144
  last_modified_at: 2022-03-01 21:18:57.226177
