id: ABDDA2BAC
title: 'Chapter 10: Dhyānapāramitā'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:18:57.362522
  last_modified_at: 2022-03-01 21:18:57.362528
