id: ABDDA2BAC
title: Colophon
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:18:57.380822
  last_modified_at: 2022-03-01 21:18:57.380825
